### PR TITLE
Parallelize 1: Add fixes to the learner tensor implementation

### PR DESCRIPTION
**Pull request by DarshalShetty**

### CODE REVIEW

**Comment by themetaschemer** [comment]
This includes changes from Parallelize 0 ... you have to create the PR so that it is supposed to merge into parallelize 0, not the root branch (in this case parallelize/fix-learner). I think the same issue exists for the other PRs (which should point to the n-1'th branch).

**Comment by DarshalShetty** [comment]
I think I fixed it now

**Comment by themetaschemer** [comment]
[[fix-learner]use one kernel in ext2-∇ and accelerate all ext* function calls](https://github.com/themetaschemer/malt/pull/62/commits/f7edcd4935a9efecb40c5cbf510ecc4c8c04b7f8)

This commit only seems to add a couple of exports to learner ... is that what was really intended, or is this commit mis labeled/incomplete?

**Comment by DarshalShetty** [comment]
This was intended. The commit message is from original branch in https://github.com/themetaschemer/malt/pull/60 before we split it into several branches. The original commit was split into several branches. The original commit uses `tolerance` in malted/test/test-A-core.rkt. Since this change was made in `malted`, I had to export `tolerance` from every implementation.

**Comment by themetaschemer** [comment]
Okay, then just reword the commit message. 
A. 
    On Monday, September 16, 2024 at 12:00:54 PM PDT, Darshal Shetty ***@***.***> wrote:  
 
 


This was intended. The commit message is from original branch in #60 before we split it into several branches. The original commit was split into several branches. The original commit uses tolerance in malted/test/test-A-core.rkt. Since this change was made in malted, I had to export tolerance from every implementation.

**Comment by DarshalShetty** [comment]
Is rewording the message a good idea? The commit message helps me understand the context around why the change was made by referring to the same message in the original branch before being split. Since these commits will be squashed when merging with the main branch, rewording it seems redundant, right? Unless you want to merge this PR without squashing the commits?

**Comment by themetaschemer** [comment]
I like to squash minor commits, but major commits should be kept. If you think this commit will be squashed, then it's fine. 
A. 
    On Monday, September 16, 2024 at 06:00:10 PM PDT, Darshal Shetty ***@***.***> wrote:  
 
 


Is rewording the message a good idea? The commit message helps me understand the context around why the change was made by referring to the same message in the original branch before being split. Since these commits will be squashed when merging with the main branch, rewording it seems redundant, right? Unless you want to merge this PR without squashing the commits?

**Comment by DarshalShetty** [comment]
Let's squash the fix-* branch commits into main since they are all minor changes. I'll fix the commit messages for the add-* branches as you come across them.

**Comment by themetaschemer** [comment]
Okay.
A.
    On Monday, September 16, 2024 at 07:49:04 PM PDT, Darshal Shetty ***@***.***> wrote:  
 
 


Let's squash the fix-* branch commits into main since they are all minor changes. I'll fix the commit messages for the add-* branches as you come across them.

**Pull request merged**
